version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/todo.db
    volumes:
      - ./data:/app/data
    depends_on:
      - db-init

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db-init:
    build: ./backend
    command: ["go", "run", "cmd/main.go", "--init-db"]
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/todo.db

volumes:
  data: